[IN-1974] Packer up the BaseOS Catalina 10.15.7
bitrise-io/macos-bootstrap pull request #6
Opened 2020-10-14 14:22 UTC by bitrise-tom

### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [ ] The tool I added is stable, and __does not require frequent updates__. _Preinstalled tools on the LTS stacks
  are not updated, so if the tool requires frequent updates you should handle the installation on-demand (see: [Install Any Additional Tool - DevCenter](https://bitrise-io.github.io/devcenter/tips-and-tricks/install-additional-tools/) for more information)_
- [ ] I added a version report line to [`system_report.sh`](/system_report.sh) for the new tool(s) I added
- [ ] I have added an entry to the CHANGELOG.md with a revisionID (the current date and the number of the change e.g.: 2019_10_11_1) and a brief description of the actual change
- [ ] I have updated the revisionID in [bitrise_profile](roles/profiles/files/bitrise_profile) **BITRISE_OSX_STACK_REV_ID** with the one I just created in the CHANGELOG.md

2020-10-14 14:26 UTC, lmesz-bitrise requested changes

2020-10-14 14:26 UTC, lmesz-bitrise commented on packer/run_packer.sh
> +sudo -E packer build -debug -color=true -timestamp-ui $1
As far as I remember if packer is called with `-debug` it expects user interaction. I think for automation it should be removed.

2020-10-14 14:27 UTC, lmesz-bitrise commented on packer/run_packer.sh
> +sudo -E packer build -debug -color=true -timestamp-ui $1
oh :)

2020-10-14 14:27 UTC, lmesz-bitrise submitted a review, later dismissed

2020-10-14 14:27 UTC, fehersanyi-bitrise commented on packer/baseOS.json
> +    {
do we really need this precheck?

2020-10-14 14:28 UTC, fehersanyi-bitrise approved these changes

2020-10-15 09:20 UTC, bitrise-tom commented on packer/baseOS.json
> +    {
it was really useful for debugging just to make sure we are the vagrant user - it's an extra 10 seconds

2020-10-15 09:30 UTC, fehersanyi-bitrise approved these changes

2020-10-15 09:53 UTC, lmesz-bitrise approved these changes

2020-10-15 12:05 UTC, merged