[IN-1978] create baseXcode 11.6 layer
bitrise-io/macos-bootstrap pull request #8
Opened 2020-10-15 10:59 UTC by bitrise-tom

### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [ ] The tool I added is stable, and __does not require frequent updates__. _Preinstalled tools on the LTS stacks
  are not updated, so if the tool requires frequent updates you should handle the installation on-demand (see: [Install Any Additional Tool - DevCenter](https://bitrise-io.github.io/devcenter/tips-and-tricks/install-additional-tools/) for more information)_
- [ ] I updated the corresponding tests if there were any.
- [ ] I added a version report line to [`system_report.sh`](/system_report.sh) for the new tool(s) I added
- [ ] I have added an entry to the CHANGELOG.md with a revisionID (the current date and the number of the change e.g.: 2019_10_11_1) and a brief description of the actual change
- [ ] I have updated the revisionID in [bitrise_profile](roles/profiles/files/bitrise_profile) **BITRISE_OSX_STACK_REV_ID** with the one I just created in the CHANGELOG.md

2020-10-15 11:00 UTC, fehersanyi-bitrise approved these changes

2020-10-15 11:10 UTC, lmesz-bitrise requested changes

2020-10-15 11:10 UTC, lmesz-bitrise commented on baseXcode-playbook.yml
> +    - XCODE_INSTALL_PASSWORD: 12Budapest99
I wouldn't add a password as plaintext to the repository

2020-10-15 11:10 UTC, lmesz-bitrise commented on packer/run_packer.sh
> +if test z$2 = z ; then
Duplicates of the previous if

2020-10-15 11:10 UTC, lmesz-bitrise commented on roles/install-xcode/tasks/main.yml
> -- name: Cleanup cached downloads
It cleans up the xcode dmg too, so I wouldn't remove it.

2020-10-15 12:05 UTC, bitrise-tom commented on baseXcode-playbook.yml
> +    - XCODE_INSTALL_PASSWORD: 12Budapest99
shyte, you are right

2020-10-15 12:08 UTC, bitrise-tom commented on packer/run_packer.sh
> +if test z$2 = z ; then
no, this is $1 vs $2

2020-10-15 12:13 UTC, lmesz-bitrise commented on packer/run_packer.sh
> +if test z$2 = z ; then
Yikkks right

2020-10-16 07:20 UTC, MrBlaise commented on baseXcode-playbook.yml
> +    - XCODE_INSTALL_USER: <XXXX>
Why don't we use ansible vault?

2020-10-16 07:26 UTC, bitrise-tom commented on roles/install-xcode/tasks/main.yml
> -- name: Cleanup cached downloads
This is moved into the role `install-simulators`

2020-10-16 07:28 UTC, bitrise-tom commented on baseXcode-playbook.yml
> +    - XCODE_INSTALL_USER: <XXXX>
because this is proof that we can build the images first, I'm poking hardocded things in everywhere just to get a clean run first.
Eventually this will use bitrise secrets as usual

2020-10-16 07:28 UTC, MrBlaise commented on baseXcode-playbook.yml
> +    - XCODE_INSTALL_USER: <XXXX>
I see, okay.

2020-10-16 07:30 UTC, MrBlaise approved these changes

2020-10-21 10:33 UTC, Kanan-Bitrise approved these changes

2020-10-21 10:34 UTC, lmesz-bitrise approved these changes

2020-10-21 10:35 UTC, merged